steps:
- id: terraform-init
  name: hashicorp/terraform:1.0.0
  args: ['init']

- id: terraform-apply
  name: hashicorp/terraform:1.0.0
  args: ['apply', '-auto-approve']
  env:
    - 'TF_VAR_project_id=${_PROJECT_ID}'

timeout: 2600s